sudo: required
language: generic

before_install:
- openssl aes-256-cbc -K $encrypted_bcd7f7f4ca94_key -iv $encrypted_bcd7f7f4ca94_iv
  -in id_rsa.enc -out id_rsa -d

before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 id_rsa
  - ssh-add id_rsa

deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master

after_deploy:
  - rm id_rsa
