version: "3"

services:

  website:
    image: panoramadv/website
    env_file: .env
    volumes:
      - ../media:/app/media
      - ../static:/app/static
    networks:
      - webnet

  build:
    image: yafas/build-trigger
    volumes:
      - ./spec.yaml:/app/spec.yaml
    env_file: .env
    networks:
      - webnet

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../media:/var/media
      - ../static:/var/static
    networks:
      - webnet

networks:
  webnet:
